import daisyui from "daisyui";


export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  safelist: [
    "data-theme-cupcake",
    "data-theme-bumblebee",
    "data-theme-emerald",
    "data-theme-corporate",
    "data-theme-synthwave",
    "data-theme-retro",
    "data-theme-cyberpunk",
    "data-theme-valentine",
    "data-theme-halloween",
    "data-theme-garden",
    "data-theme-forest",
    "data-theme-aqua",
    "data-theme-lofi",
    "data-theme-pastel",
    "data-theme-fantasy",
    "data-theme-wireframe",
    "data-theme-black",
    "data-theme-luxury",
    "data-theme-dracula",
    "data-theme-cmyk",
    "data-theme-autumn",
    "data-theme-business",
  ],
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
    ],
  },
};
